### PR TITLE
support custom less options

### PR DESCRIPTION
**Pull request by jfgodoy**
this pull request add support for custom less options, for example:
```
"css": {
    "module": "kraken-devtools/plugins/less",
    "files": "/css/**/*.css",
    "relativeUrls": true
}
```

Is the api ok? or prefer this way:
```
"css": {
    "module": "kraken-devtools/plugins/less",
    "files": "/css/**/*.css",
    "options": {
        "relativeUrls": true
    }
}
```

### CODE REVIEW

**Comment by jasisk** [comment]
Just adding a quick note here: build failure on 0.11 due to node-sass. Disregard.

**Comment by aredridel** [comment]
Might want to disable the node-sass test on incompatible platforms and document that it's not ready yet, but otherwise test, rather than disabling all tests for iojs.

**Comment by aredridel** [comment]
https://github.com/krakenjs/kraken-devtools/pull/52 should fix the node-sass failure

**Comment by grawk** [comment]
@jfgodoy would you have time to re-open this PR against the new separate plugin: [construx-less](https://github.com/krakenjs/construx-less) ? We are going to recommend people migrate to the new, more atomic `construx` family of modules and discourage further code changes to this module.

**Pull request closed without merging**
