### PR TITLE
Fix #43

### LINKED ISSUE #43: Possible security issue
If I try to load the URL `/anything.anything)`, I get this error:
<pre>SyntaxError: Caught exception: Invalid regular expression: //(.*)\.anything:)$/: Unmatched ')'
SyntaxError: Caught exception: Invalid regular expression: //(.*)\.anything:)$/: Unmatched ')'
  at new RegExp (<anonymous>:null:null)
  at start (node_modules/kraken-devtools/lib/middleware.js:45:21)
  at fn (node_modules/kraken-devtools/node_modules/async/lib/async.js:582:34)
  at Object._onImmediate (node_modules/kraken-devtools/node_modules/async/lib/async.js:498:34)
  at processImmediate [as _immediateCallback] (timers.js:336:15)</pre>

I see the code:
<pre>ext = path.extname(req.path).replace('.', '\\.');
regex = new RegExp(dir + '/(.*)' + ext +'$', 'i');</pre>

Inject the URL (user input) in a RegExp is a very bad idea IMHO.

### PR DESCRIPTION
**Pull request by kylekatarnls**
Maybe it could be done withour RegExp but first this will fix the bug.

### CODE REVIEW

**Comment by grawk** [comment]
Hi @kylekatarnls,

Can you please describe (either here or in a comment above the regex) what the expected functionality of this proposed regex is, as well as add an additional unit test (or multiple tests) to verify it does what is expected?

Thanks!

**Comment by kylekatarnls** [comment]
I saw errors in my log due to URLs like /foo.bar) I consider it's not safe that a user with a simple input like that could trigger unexpected errors. So I parse with this fix the RegExp symbols as they should be,  the RegExp must include the path as string and not as a RegExp that can be executed.

**Comment by jasisk** [comment]
Worth reminding that devtools is intended to be used as a development-only tool. One should be precompiling assets for production.

**Comment by kylekatarnls** [comment]
Yes but it's also mean that some specials URLs (with *.()[]{}$^) will be bugged.

**Comment by jasisk** [comment]
Fixed by #38.

**Pull request closed without merging**
