### PR TITLE
Add grunt-cli as a dev dependency

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by grawk** [comment]
:+1:

**Comment by jasisk** [comment]
I wish there was a way to conditionally install modules if not found globally. :(

**Comment by aredridel** [comment]
Hehe. I'm glad there's not! If you app requires it, install it! Depending on a global's just silly.

**Comment by jasisk** [comment]
True but in (rare) cases like grunt where the cli is split out from the engine. Not saying it's a design I'd choose now ... :grinning:

**Comment by aredridel** [comment]
I say especially then, since the lifecycles of globals vs apps are managed independently, there's no guarantee that the global will stay in place, and there's no thing expressing that that is in fact supposed to be there globally.

**Pull request merged**
