### PR TITLE
Add support for locale groups

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by grawk** [comment]
:+1:

**Comment by aredridel** [comment]
Sweet! If you publish this, this clears a user's bug!

**Comment by grawk** [comment]
OK will do.

**Comment by grawk** [comment]
should we consider this as a patch or a minor release? it feels like a patch but of course it could change the behavior of the middleware for some

**Comment by aredridel** [comment]
Hm. That'd make it technically breaking but distantly unlikely; does add a feature, I'm inclined to say minor.

**Comment by grawk** [comment]
OK. What bug does this fix so I can reference in the changelog?

**Comment by aredridel** [comment]
It allows locales like `en-EMEA`, for grouping a bunch of countries.

**Comment by grawk** [comment]
oh of course. that's clear from the unit test. i just thought maybe an issue had been filed on another module (since there was none filed here)

**Comment by aredridel** [comment]
Nope. I may have beaten them to the punch

**Pull request merged**
