### PR TITLE
#45 Handle plugins

### PR DESCRIPTION
**Pull request by kylekatarnls**
This should allow to configure stylus with use: ["nib", "jeet"] and so on

### CODE REVIEW

**Comment by jasisk** [comment]
Does this work correctly? AFAIK, at least `nib` returns a generator that needs to be called.

**Comment by kylekatarnls** [comment]
Sorry yes, the fix is there.

**Comment by jasisk** [comment]
This introduces an opportunity for us to throw in a fairly non-meaningful way: either if the module doesn't resolve or if it doesn't return a function. Those two cases should be caught, and the callback called (see the [less implementation](https://github.com/krakenjs/kraken-devtools/blob/340d35efe50c6a37b914e85836fbf5009d5e9d15/plugins/less.js#L35-L47) for a case of having to catch a synchronous error like that).

Also, a couple of tests would be great, particularly as we'll be factoring out the plugins soon.

**Comment by grawk** [comment]
Hi @jasisk and @kylekatarnls I've published the `construx-stylus` plugin to replace the currently embedded stylus plugin module here. As such, can you please look at that module and file any issues you feel are the difference between the current implementation and the desired implementation for stylus plugins?
https://github.com/krakenjs/construx-stylus

I apologize that I didn't carry over any applicable commits. Hopefully the contributor block is a good compromise. @kylekatarnls please let me know what name/email you'd like me to use for you here:
https://github.com/krakenjs/construx-stylus/issues/4

**Pull request closed without merging**
