### PR TITLE
bump node-sass@2.0.1

### PR DESCRIPTION
**Pull request by jasisk**
... in DevDeps for travis and whatnot.

### CODE REVIEW

**Comment by jasisk** [comment]
Breaking on 0.11, not breaking on 0.10 or 0.12 (except for the dust test failing).

**Comment by grawk** [comment]
:+1:

**Comment by pvenkatakrishnan** [comment]
hmmm but the build is failing on 0.10 as well ?

**Comment by jasisk** [comment]
Due to dust.

**Comment by grawk** [comment]
We could take Aria's two PR's first, that way a) travis wouldn't run on 0.11 and b) dust tests wouldn't fail

**Comment by pvenkatakrishnan** [comment]
ok

**Comment by grawk** [comment]
Oh. They already were.. restarting tests

**Comment by jasisk** [comment]
Rebased.

**Comment by jasisk** [comment]
Ugh. node-sass failing with iojs and this is a known issue. Tracking node-sass v3.0.0 for the fix.

**Comment by aredridel** [comment]
Disabling the node-sass tests if we're on a platform with module version 42 makes more sense than disabling iojs tests as a whole, I think. Less is left uncovered, and we can document that the break is known.

**Comment by jasisk** [comment]
_Sigh._

**Comment by grawk** [comment]
:+1:

**Comment by aredridel** [comment]
Most effort for one-line change ever.

**Comment by jasisk** [comment]
Everything is the worst.

**Pull request merged**
